// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeWaitingResultMessage.xml' the '27/06/2012 15:55:11'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class ExchangeWaitingResultMessage : NetworkMessage
	{
		public const uint Id = 5786;
		public override uint MessageId
		{
			get
			{
				return 5786;
			}
		}
		
		public bool bwait;
		
		public ExchangeWaitingResultMessage()
		{
		}
		
		public ExchangeWaitingResultMessage(bool bwait)
		{
			this.bwait = bwait;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(bwait);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			bwait = reader.ReadBoolean();
		}
	}
}
