// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeObjectMoveKamaMessage.xml' the '27/06/2012 15:55:10'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class ExchangeObjectMoveKamaMessage : NetworkMessage
	{
		public const uint Id = 5520;
		public override uint MessageId
		{
			get
			{
				return 5520;
			}
		}
		
		public int quantity;
		
		public ExchangeObjectMoveKamaMessage()
		{
		}
		
		public ExchangeObjectMoveKamaMessage(int quantity)
		{
			this.quantity = quantity;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(quantity);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			quantity = reader.ReadInt();
		}
	}
}
