// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeStartOkNpcTradeMessage.xml' the '27/06/2012 15:55:11'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ExchangeStartOkNpcTradeMessage : NetworkMessage
	{
		public const uint Id = 5785;
		public override uint MessageId
		{
			get
			{
				return 5785;
			}
		}
		
		public int npcId;
		
		public ExchangeStartOkNpcTradeMessage()
		{
		}
		
		public ExchangeStartOkNpcTradeMessage(int npcId)
		{
			this.npcId = npcId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(npcId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			npcId = reader.ReadInt();
		}
	}
}
