// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeBidHouseInListAddedMessage.xml' the '27/06/2012 15:55:09'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class ExchangeBidHouseInListAddedMessage : NetworkMessage
	{
		public const uint Id = 5949;
		public override uint MessageId
		{
			get
			{
				return 5949;
			}
		}
		
		public int itemUID;
		public int objGenericId;
		public short powerRate;
		public bool overMax;
		public Types.ObjectEffect[] effects;
		public int[] prices;
		
		public ExchangeBidHouseInListAddedMessage()
		{
		}
		
		public ExchangeBidHouseInListAddedMessage(int itemUID, int objGenericId, short powerRate, bool overMax, Types.ObjectEffect[] effects, int[] prices)
		{
			this.itemUID = itemUID;
			this.objGenericId = objGenericId;
			this.powerRate = powerRate;
			this.overMax = overMax;
			this.effects = effects;
			this.prices = prices;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(itemUID);
			writer.WriteInt(objGenericId);
			writer.WriteShort(powerRate);
			writer.WriteBoolean(overMax);
			writer.WriteUShort((ushort)effects.Count());
			foreach (var entry in effects)
			{
				writer.WriteShort(entry.TypeId);
				entry.Serialize(writer);
			}
			writer.WriteUShort((ushort)prices.Count());
			foreach (var entry in prices)
			{
				writer.WriteInt(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			itemUID = reader.ReadInt();
			objGenericId = reader.ReadInt();
			powerRate = reader.ReadShort();
			overMax = reader.ReadBoolean();
			int limit = reader.ReadUShort();
			effects = new Types.ObjectEffect[limit];
			for (int i = 0; i < limit; i++)
			{
				(effects as Types.ObjectEffect[])[i] = Types.ProtocolTypeManager.GetInstance<Types.ObjectEffect>(reader.ReadShort());
				(effects as Types.ObjectEffect[])[i].Deserialize(reader);
			}
			limit = reader.ReadUShort();
			prices = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				(prices as int[])[i] = reader.ReadInt();
			}
		}
	}
}
