// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeGoldPaymentForCraftMessage.xml' the '27/06/2012 15:55:09'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ExchangeGoldPaymentForCraftMessage : NetworkMessage
	{
		public const uint Id = 5833;
		public override uint MessageId
		{
			get
			{
				return 5833;
			}
		}
		
		public bool onlySuccess;
		public int goldSum;
		
		public ExchangeGoldPaymentForCraftMessage()
		{
		}
		
		public ExchangeGoldPaymentForCraftMessage(bool onlySuccess, int goldSum)
		{
			this.onlySuccess = onlySuccess;
			this.goldSum = goldSum;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(onlySuccess);
			writer.WriteInt(goldSum);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			onlySuccess = reader.ReadBoolean();
			goldSum = reader.ReadInt();
			if ( goldSum < 0 )
			{
				throw new Exception("Forbidden value on goldSum = " + goldSum + ", it doesn't respect the following condition : goldSum < 0");
			}
		}
	}
}
