// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeObjectAddedMessage.xml' the '27/06/2012 15:55:10'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ExchangeObjectAddedMessage : ExchangeObjectMessage
	{
		public const uint Id = 5516;
		public override uint MessageId
		{
			get
			{
				return 5516;
			}
		}
		
		public Types.ObjectItem @object;
		
		public ExchangeObjectAddedMessage()
		{
		}
		
		public ExchangeObjectAddedMessage(bool remote, Types.ObjectItem @object)
			 : base(remote)
		{
			this.@object = @object;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			@object.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			@object = new Types.ObjectItem();
			@object.Deserialize(reader);
		}
	}
}
