// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeMountFreeFromPaddockMessage.xml' the '27/06/2012 15:55:09'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ExchangeMountFreeFromPaddockMessage : NetworkMessage
	{
		public const uint Id = 6055;
		public override uint MessageId
		{
			get
			{
				return 6055;
			}
		}
		
		public string name;
		public short worldX;
		public short worldY;
		public string liberator;
		
		public ExchangeMountFreeFromPaddockMessage()
		{
		}
		
		public ExchangeMountFreeFromPaddockMessage(string name, short worldX, short worldY, string liberator)
		{
			this.name = name;
			this.worldX = worldX;
			this.worldY = worldY;
			this.liberator = liberator;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(name);
			writer.WriteShort(worldX);
			writer.WriteShort(worldY);
			writer.WriteUTF(liberator);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			name = reader.ReadUTF();
			worldX = reader.ReadShort();
			if ( worldX < -255 || worldX > 255 )
			{
				throw new Exception("Forbidden value on worldX = " + worldX + ", it doesn't respect the following condition : worldX < -255 || worldX > 255");
			}
			worldY = reader.ReadShort();
			if ( worldY < -255 || worldY > 255 )
			{
				throw new Exception("Forbidden value on worldY = " + worldY + ", it doesn't respect the following condition : worldY < -255 || worldY > 255");
			}
			liberator = reader.ReadUTF();
		}
	}
}
