// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeObjectModifyPricedMessage.xml' the '27/06/2012 15:55:10'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ExchangeObjectModifyPricedMessage : ExchangeObjectMovePricedMessage
	{
		public const uint Id = 6238;
		public override uint MessageId
		{
			get
			{
				return 6238;
			}
		}
		
		
		public ExchangeObjectModifyPricedMessage()
		{
		}
		
		public ExchangeObjectModifyPricedMessage(int objectUID, int quantity, int price)
			 : base(objectUID, quantity, price)
		{
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
		}
	}
}
