// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeClearPaymentForCraftMessage.xml' the '27/06/2012 15:55:09'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class ExchangeClearPaymentForCraftMessage : NetworkMessage
	{
		public const uint Id = 6145;
		public override uint MessageId
		{
			get
			{
				return 6145;
			}
		}
		
		public sbyte paymentType;
		
		public ExchangeClearPaymentForCraftMessage()
		{
		}
		
		public ExchangeClearPaymentForCraftMessage(sbyte paymentType)
		{
			this.paymentType = paymentType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(paymentType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			paymentType = reader.ReadSByte();
		}
	}
}
