// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SetEnablePVPRequestMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class SetEnablePVPRequestMessage : NetworkMessage
	{
		public const uint Id = 1810;
		public override uint MessageId
		{
			get
			{
				return 1810;
			}
		}
		
		public bool enable;
		
		public SetEnablePVPRequestMessage()
		{
		}
		
		public SetEnablePVPRequestMessage(bool enable)
		{
			this.enable = enable;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(enable);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			enable = reader.ReadBoolean();
		}
	}
}
