// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayGroupMonsterInformations.xml' the '27/06/2012 15:55:15'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class GameRolePlayGroupMonsterInformations : GameRolePlayActorInformations
	{
		public const uint Id = 160;
		public override short TypeId
		{
			get
			{
				return 160;
			}
		}
		
		public Types.GroupMonsterStaticInformations staticInfos;
		public short ageBonus;
		public sbyte lootShare;
		public sbyte alignmentSide;
		public bool keyRingBonus;
		
		public GameRolePlayGroupMonsterInformations()
		{
		}
		
		public GameRolePlayGroupMonsterInformations(int contextualId, Types.EntityLook look, Types.EntityDispositionInformations disposition, Types.GroupMonsterStaticInformations staticInfos, short ageBonus, sbyte lootShare, sbyte alignmentSide, bool keyRingBonus)
			 : base(contextualId, look, disposition)
		{
			this.staticInfos = staticInfos;
			this.ageBonus = ageBonus;
			this.lootShare = lootShare;
			this.alignmentSide = alignmentSide;
			this.keyRingBonus = keyRingBonus;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(staticInfos.TypeId);
			staticInfos.Serialize(writer);
			writer.WriteShort(ageBonus);
			writer.WriteSByte(lootShare);
			writer.WriteSByte(alignmentSide);
			writer.WriteBoolean(keyRingBonus);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			staticInfos = ProtocolTypeManager.GetInstance<Types.GroupMonsterStaticInformations>(reader.ReadShort());
			staticInfos.Deserialize(reader);
			ageBonus = reader.ReadShort();
			if ( ageBonus < -1 || ageBonus > 1000 )
			{
				throw new Exception("Forbidden value on ageBonus = " + ageBonus + ", it doesn't respect the following condition : ageBonus < -1 || ageBonus > 1000");
			}
			lootShare = reader.ReadSByte();
			if ( lootShare < -1 || lootShare > 8 )
			{
				throw new Exception("Forbidden value on lootShare = " + lootShare + ", it doesn't respect the following condition : lootShare < -1 || lootShare > 8");
			}
			alignmentSide = reader.ReadSByte();
			keyRingBonus = reader.ReadBoolean();
		}
	}
}
