// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MonsterInGroupLightInformations.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class MonsterInGroupLightInformations
	{
		public const uint Id = 395;
		public virtual short TypeId
		{
			get
			{
				return 395;
			}
		}
		
		public int creatureGenericId;
		public sbyte grade;
		
		public MonsterInGroupLightInformations()
		{
		}
		
		public MonsterInGroupLightInformations(int creatureGenericId, sbyte grade)
		{
			this.creatureGenericId = creatureGenericId;
			this.grade = grade;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteInt(creatureGenericId);
			writer.WriteSByte(grade);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			creatureGenericId = reader.ReadInt();
			grade = reader.ReadSByte();
			if ( grade < 0 )
			{
				throw new Exception("Forbidden value on grade = " + grade + ", it doesn't respect the following condition : grade < 0");
			}
		}
	}
}
