// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MonsterInGroupInformations.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class MonsterInGroupInformations : MonsterInGroupLightInformations
	{
		public const uint Id = 144;
		public override short TypeId
		{
			get
			{
				return 144;
			}
		}
		
		public Types.EntityLook look;
		
		public MonsterInGroupInformations()
		{
		}
		
		public MonsterInGroupInformations(int creatureGenericId, sbyte grade, Types.EntityLook look)
			 : base(creatureGenericId, grade)
		{
			this.look = look;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			look.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			look = new Types.EntityLook();
			look.Deserialize(reader);
		}
	}
}
