// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BasicPingMessage.xml' the '27/06/2012 15:54:55'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class BasicPingMessage : NetworkMessage
	{
		public const uint Id = 182;
		public override uint MessageId
		{
			get
			{
				return 182;
			}
		}
		
		public bool quiet;
		
		public BasicPingMessage()
		{
		}
		
		public BasicPingMessage(bool quiet)
		{
			this.quiet = quiet;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(quiet);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			quiet = reader.ReadBoolean();
		}
	}
}
