// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BasicPongMessage.xml' the '27/06/2012 15:54:55'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class BasicPongMessage : NetworkMessage
	{
		public const uint Id = 183;
		public override uint MessageId
		{
			get
			{
				return 183;
			}
		}
		
		public bool quiet;
		
		public BasicPongMessage()
		{
		}
		
		public BasicPongMessage(bool quiet)
		{
			this.quiet = quiet;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(quiet);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			quiet = reader.ReadBoolean();
		}
	}
}
