// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobAllowMultiCraftRequestSetMessage.xml' the '27/06/2012 15:55:03'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class JobAllowMultiCraftRequestSetMessage : NetworkMessage
	{
		public const uint Id = 5749;
		public override uint MessageId
		{
			get
			{
				return 5749;
			}
		}
		
		public bool enabled;
		
		public JobAllowMultiCraftRequestSetMessage()
		{
		}
		
		public JobAllowMultiCraftRequestSetMessage(bool enabled)
		{
			this.enabled = enabled;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(enabled);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			enabled = reader.ReadBoolean();
		}
	}
}
