// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobListedUpdateMessage.xml' the '27/06/2012 15:55:03'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class JobListedUpdateMessage : NetworkMessage
	{
		public const uint Id = 6016;
		public override uint MessageId
		{
			get
			{
				return 6016;
			}
		}
		
		public bool addedOrDeleted;
		public sbyte jobId;
		
		public JobListedUpdateMessage()
		{
		}
		
		public JobListedUpdateMessage(bool addedOrDeleted, sbyte jobId)
		{
			this.addedOrDeleted = addedOrDeleted;
			this.jobId = jobId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(addedOrDeleted);
			writer.WriteSByte(jobId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			addedOrDeleted = reader.ReadBoolean();
			jobId = reader.ReadSByte();
			if ( jobId < 0 )
			{
				throw new Exception("Forbidden value on jobId = " + jobId + ", it doesn't respect the following condition : jobId < 0");
			}
		}
	}
}
