// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StartupActionsExecuteMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class StartupActionsExecuteMessage : NetworkMessage
	{
		public const uint Id = 1302;
		public override uint MessageId
		{
			get
			{
				return 1302;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
