// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'InventoryPresetUseResultMessage.xml' the '27/06/2012 15:55:12'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Messages
{
	public class InventoryPresetUseResultMessage : NetworkMessage
	{
		public const uint Id = 6163;
		public override uint MessageId
		{
			get
			{
				return 6163;
			}
		}
		
		public sbyte presetId;
		public sbyte code;
		public IEnumerable<byte> unlinkedPosition;
		
		public InventoryPresetUseResultMessage()
		{
		}
		
		public InventoryPresetUseResultMessage(sbyte presetId, sbyte code, IEnumerable<byte> unlinkedPosition)
		{
			this.presetId = presetId;
			this.code = code;
			this.unlinkedPosition = unlinkedPosition;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(presetId);
			writer.WriteSByte(code);
			writer.WriteUShort((ushort)unlinkedPosition.Count());
			foreach (var entry in unlinkedPosition)
			{
				writer.WriteByte(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			presetId = reader.ReadSByte();
			if ( presetId < 0 )
			{
				throw new Exception("Forbidden value on presetId = " + presetId + ", it doesn't respect the following condition : presetId < 0");
			}
			code = reader.ReadSByte();
			if ( code < 0 )
			{
				throw new Exception("Forbidden value on code = " + code + ", it doesn't respect the following condition : code < 0");
			}
			int limit = reader.ReadUShort();
			unlinkedPosition = new byte[limit];
			for (int i = 0; i < limit; i++)
			{
				(unlinkedPosition as byte[])[i] = reader.ReadByte();
			}
		}
	}
}
