// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'InventoryPresetUseMessage.xml' the '27/06/2012 15:55:12'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class InventoryPresetUseMessage : NetworkMessage
	{
		public const uint Id = 6167;
		public override uint MessageId
		{
			get
			{
				return 6167;
			}
		}
		
		public sbyte presetId;
		
		public InventoryPresetUseMessage()
		{
		}
		
		public InventoryPresetUseMessage(sbyte presetId)
		{
			this.presetId = presetId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(presetId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			presetId = reader.ReadSByte();
			if ( presetId < 0 )
			{
				throw new Exception("Forbidden value on presetId = " + presetId + ", it doesn't respect the following condition : presetId < 0");
			}
		}
	}
}
