// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AlignmentSideEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum AlignmentSideEnum
	{
		ALIGNMENT_UNKNOWN = -2,
		ALIGNMENT_WITHOUT = -1,
		ALIGNMENT_NEUTRAL = 0,
		ALIGNMENT_ANGEL = 1,
		ALIGNMENT_EVIL = 2,
		ALIGNMENT_MERCENARY = 3,
	}
}
