// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterSpellModificationTypeEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum CharacterSpellModificationTypeEnum
	{
		INVALID_MODIFICATION = 0,
		RANGEABLE = 1,
		DAMAGE = 2,
		BASE_DAMAGE = 3,
		HEAL_BONUS = 4,
		AP_COST = 5,
		CAST_INTERVAL = 6,
		CAST_INTERVAL_SET = 7,
		CRITICAL_HIT_BONUS = 8,
		CAST_LINE = 9,
		LOS = 10,
		MAX_CAST_PER_TURN = 11,
		MAX_CAST_PER_TARGET = 12,
		RANGE = 13,
	}
}
