// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChatErrorEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum ChatErrorEnum
	{
		CHAT_ERROR_UNKNOWN = 0,
		CHAT_ERROR_RECEIVER_NOT_FOUND = 1,
		CHAT_ERROR_INTERIOR_MONOLOGUE = 2,
		CHAT_ERROR_NO_GUILD = 3,
		CHAT_ERROR_NO_PARTY = 4,
		CHAT_ERROR_ALIGN = 5,
		CHAT_ERROR_INVALID_MAP = 6,
		CHAT_ERROR_NO_PARTY_ARENA = 7,
		CHAT_ERROR_NO_TEAM = 8,
	}
}
