// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ClientInstallTypeEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum ClientInstallTypeEnum
	{
		CLIENT_INSTALL_UNKNOWN = 0,
		CLIENT_BUNDLE = 1,
		CLIENT_STREAMING = 2,
	}
}
