// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ConsoleMessageTypeEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum ConsoleMessageTypeEnum
	{
		CONSOLE_TEXT_MESSAGE = 0,
		CONSOLE_INFO_MESSAGE = 1,
		CONSOLE_ERR_MESSAGE = 2,
	}
}
