// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CraftResultEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum CraftResultEnum
	{
		CRAFT_IMPOSSIBLE = 0,
		CRAFT_FAILED = 1,
		CRAFT_SUCCESS = 2,
		CRAFT_NEUTRAL = 3,
	}
}
