// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'DebugLevelEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum DebugLevelEnum
	{
		LEVEL_TRACE = 0,
		LEVEL_DEBUG = 1,
		LEVEL_INFO = 2,
		LEVEL_WARN = 3,
		LEVEL_ERROR = 4,
		LEVEL_FATAL = 5,
	}
}
