// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightDispellableEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum FightDispellableEnum
	{
		DISPELLABLE = 1,
		DISPELLABLE_BY_DEATH = 2,
		DISPELLABLE_BY_STRONG_DISPEL = 3,
		REALLY_NOT_DISPELLABLE = 4,
	}
}
