// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightOutcomeEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum FightOutcomeEnum
	{
		RESULT_LOST = 0,
		RESULT_DRAW = 1,
		RESULT_VICTORY = 2,
		RESULT_TAX = 5,
		RESULT_DEFENDER_GROUP = 6,
	}
}
