// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightSpellCastCriticalEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum FightSpellCastCriticalEnum
	{
		NORMAL = 1,
		CRITICAL_HIT = 2,
		CRITICAL_FAIL = 3,
	}
}
