// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightOptionsEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum FightOptionsEnum
	{
		FIGHT_OPTION_SET_SECRET = 0,
		FIGHT_OPTION_SET_TO_PARTY_ONLY = 1,
		FIGHT_OPTION_SET_CLOSED = 2,
		FIGHT_OPTION_ASK_FOR_HELP = 3,
	}
}
