// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildInvitationStateEnum.as' the '27/06/2012 15:55:17'

namespace BiM.Protocol.Enums
{
	public enum GuildInvitationStateEnum
	{
		GUILD_INVITATION_SENT = 1,
		GUILD_INVITATION_CANCELED = 2,
		GUILD_INVITATION_OK = 3,
	}
}
