// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'HardcoreDeathStateEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum HardcoreDeathStateEnum
	{
		DEATH_STATE_ALIVE = 0,
		DEATH_STATE_DEAD = 1,
		DEATH_STATE_WAITING_CONFIRMATION = 2,
	}
}
