// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountEquipedErrorEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum MountEquipedErrorEnum
	{
		UNSET = 0,
		SET = 1,
		RIDING = 2,
	}
}
