// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NumericalValueTypeEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum NumericalValueTypeEnum
	{
		NUMERICAL_VALUE_DEFAULT = 0,
		NUMERICAL_VALUE_COLLECT = 1,
		NUMERICAL_VALUE_CRAFT = 2,
		NUMERICAL_VALUE_PADDOCK = 3,
		NUMERICAL_VALUE_RED = 64,
		NUMERICAL_VALUE_BLUE = 65,
		NUMERICAL_VALUE_GREEN = 66,
	}
}
