// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PlayableBreedEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum PlayableBreedEnum
	{
		UNDEFINED = 0,
		Feca = 1,
		Osamodas = 2,
		Enutrof = 3,
		Sram = 4,
		Xelor = 5,
		Ecaflip = 6,
		Eniripsa = 7,
		Iop = 8,
		Cra = 9,
		Sadida = 10,
		Sacrieur = 11,
		Pandawa = 12,
		Roublard = 13,
		Zobal = 14,
		Steamer = 15,
	}
}
