// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PlayerLifeStatusEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum PlayerLifeStatusEnum
	{
		STATUS_ALIVE_AND_KICKING = 0,
		STATUS_TOMBSTONE = 1,
		STATUS_PHANTOM = 2,
	}
}
