// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PresetSaveResultEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum PresetSaveResultEnum
	{
		PRESET_SAVE_OK = 1,
		PRESET_SAVE_ERR_UNKNOWN = 2,
		PRESET_SAVE_ERR_TOO_MANY = 3,
	}
}
