// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PresetDeleteResultEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum PresetDeleteResultEnum
	{
		PRESET_DEL_OK = 1,
		PRESET_DEL_ERR_UNKNOWN = 2,
		PRESET_DEL_ERR_BAD_PRESET_ID = 3,
	}
}
