// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SequenceTypeEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum SequenceTypeEnum
	{
		SEQUENCE_SPELL = 1,
		SEQUENCE_WEAPON = 2,
		SEQUENCE_GLYPH_TRAP = 3,
		SEQUENCE_TRIGGERED = 4,
		SEQUENCE_MOVE = 5,
		SEQUENCE_CHARACTER_DEATH = 6,
		SEQUENCE_TURN_START = 7,
		SEQUENCE_TURN_END = 8,
		SEQUENCE_FIGHT_START = 9,
	}
}
