// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutBarEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum ShortcutBarEnum
	{
		GENERAL_SHORTCUT_BAR = 0,
		SPELL_SHORTCUT_BAR = 1,
	}
}
