// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SocialContactCategoryEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum SocialContactCategoryEnum
	{
		SOCIAL_CONTACT_FRIEND = 0,
		SOCIAL_CONTACT_SPOUSE = 1,
		SOCIAL_CONTACT_PARTY = 2,
		SOCIAL_CONTACT_GUILD = 3,
		SOCIAL_CONTACT_CRAFTER = 4,
	}
}
