// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeamTypeEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum TeamTypeEnum
	{
		TEAM_TYPE_PLAYER = 0,
		TEAM_TYPE_MONSTER = 1,
		TEAM_TYPE_MUTANT = 2,
		TEAM_TYPE_TAXCOLLECTOR = 3,
		TEAM_TYPE_BAD_PLAYER = 4,
	}
}
