// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeamEnum.as' the '27/06/2012 15:55:18'

namespace BiM.Protocol.Enums
{
	public enum TeamEnum
	{
		TEAM_CHALLENGER = 0,
		TEAM_DEFENDER = 1,
		TEAM_SPECTATOR = 2,
	}
}
