// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameDataPlayFarmObjectAnimationMessage.xml' the '27/06/2012 15:55:03'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Messages
{
	public class GameDataPlayFarmObjectAnimationMessage : NetworkMessage
	{
		public const uint Id = 6026;
		public override uint MessageId
		{
			get
			{
				return 6026;
			}
		}
		
		public IEnumerable<short> cellId;
		
		public GameDataPlayFarmObjectAnimationMessage()
		{
		}
		
		public GameDataPlayFarmObjectAnimationMessage(IEnumerable<short> cellId)
		{
			this.cellId = cellId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)cellId.Count());
			foreach (var entry in cellId)
			{
				writer.WriteShort(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			cellId = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(cellId as short[])[i] = reader.ReadShort();
			}
		}
	}
}
