// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayNpcQuestFlag.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Types
{
	public class GameRolePlayNpcQuestFlag
	{
		public const uint Id = 384;
		public virtual short TypeId
		{
			get
			{
				return 384;
			}
		}
		
		public IEnumerable<short> questsToValidId;
		public IEnumerable<short> questsToStartId;
		
		public GameRolePlayNpcQuestFlag()
		{
		}
		
		public GameRolePlayNpcQuestFlag(IEnumerable<short> questsToValidId, IEnumerable<short> questsToStartId)
		{
			this.questsToValidId = questsToValidId;
			this.questsToStartId = questsToStartId;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)questsToValidId.Count());
			foreach (var entry in questsToValidId)
			{
				writer.WriteShort(entry);
			}
			writer.WriteUShort((ushort)questsToStartId.Count());
			foreach (var entry in questsToStartId)
			{
				writer.WriteShort(entry);
			}
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			questsToValidId = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(questsToValidId as short[])[i] = reader.ReadShort();
			}
			limit = reader.ReadUShort();
			questsToStartId = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(questsToStartId as short[])[i] = reader.ReadShort();
			}
		}
	}
}
