// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'QuestActiveInformations.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class QuestActiveInformations
	{
		public const uint Id = 381;
		public virtual short TypeId
		{
			get
			{
				return 381;
			}
		}
		
		public short questId;
		
		public QuestActiveInformations()
		{
		}
		
		public QuestActiveInformations(short questId)
		{
			this.questId = questId;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteShort(questId);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			questId = reader.ReadShort();
			if ( questId < 0 )
			{
				throw new Exception("Forbidden value on questId = " + questId + ", it doesn't respect the following condition : questId < 0");
			}
		}
	}
}
