// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'QuestObjectiveInformations.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class QuestObjectiveInformations
	{
		public const uint Id = 385;
		public virtual short TypeId
		{
			get
			{
				return 385;
			}
		}
		
		public short objectiveId;
		public bool objectiveStatus;
		
		public QuestObjectiveInformations()
		{
		}
		
		public QuestObjectiveInformations(short objectiveId, bool objectiveStatus)
		{
			this.objectiveId = objectiveId;
			this.objectiveStatus = objectiveStatus;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteShort(objectiveId);
			writer.WriteBoolean(objectiveStatus);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			objectiveId = reader.ReadShort();
			if ( objectiveId < 0 )
			{
				throw new Exception("Forbidden value on objectiveId = " + objectiveId + ", it doesn't respect the following condition : objectiveId < 0");
			}
			objectiveStatus = reader.ReadBoolean();
		}
	}
}
