// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AchievementUpdateMessage.xml' the '27/06/2012 15:54:56'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class AchievementUpdateMessage : NetworkMessage
	{
		public const uint Id = 6207;
		public override uint MessageId
		{
			get
			{
				return 6207;
			}
		}
		
		public Types.Achievement achievement;
		
		public AchievementUpdateMessage()
		{
		}
		
		public AchievementUpdateMessage(Types.Achievement achievement)
		{
			this.achievement = achievement;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			achievement.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			achievement = new Types.Achievement();
			achievement.Deserialize(reader);
		}
	}
}
