// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AdminCommandMessage.xml' the '27/06/2012 15:54:55'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class AdminCommandMessage : NetworkMessage
	{
		public const uint Id = 76;
		public override uint MessageId
		{
			get
			{
				return 76;
			}
		}
		
		public string content;
		
		public AdminCommandMessage()
		{
		}
		
		public AdminCommandMessage(string content)
		{
			this.content = content;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(content);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			content = reader.ReadUTF();
		}
	}
}
