// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AlreadyConnectedMessage.xml' the '27/06/2012 15:54:58'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class AlreadyConnectedMessage : NetworkMessage
	{
		public const uint Id = 109;
		public override uint MessageId
		{
			get
			{
				return 109;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
