// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AuthenticationTicketMessage.xml' the '27/06/2012 15:54:58'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class AuthenticationTicketMessage : NetworkMessage
	{
		public const uint Id = 110;
		public override uint MessageId
		{
			get
			{
				return 110;
			}
		}
		
		public string lang;
		public string ticket;
		
		public AuthenticationTicketMessage()
		{
		}
		
		public AuthenticationTicketMessage(string lang, string ticket)
		{
			this.lang = lang;
			this.ticket = ticket;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(lang);
			writer.WriteUTF(ticket);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			lang = reader.ReadUTF();
			ticket = reader.ReadUTF();
		}
	}
}
