// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AuthenticationTicketWithClientPacksMessage.xml' the '27/06/2012 15:54:58'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Messages
{
	public class AuthenticationTicketWithClientPacksMessage : AuthenticationTicketMessage
	{
		public const uint Id = 6190;
		public override uint MessageId
		{
			get
			{
				return 6190;
			}
		}
		
		public IEnumerable<int> packs;
		
		public AuthenticationTicketWithClientPacksMessage()
		{
		}
		
		public AuthenticationTicketWithClientPacksMessage(string lang, string ticket, IEnumerable<int> packs)
			 : base(lang, ticket)
		{
			this.packs = packs;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteUShort((ushort)packs.Count());
			foreach (var entry in packs)
			{
				writer.WriteInt(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			int limit = reader.ReadUShort();
			packs = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				(packs as int[])[i] = reader.ReadInt();
			}
		}
	}
}
