// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ServerOptionalFeaturesMessage.xml' the '27/06/2012 15:54:58'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class ServerOptionalFeaturesMessage : NetworkMessage
	{
		public const uint Id = 6305;
		public override uint MessageId
		{
			get
			{
				return 6305;
			}
		}
		
		public IEnumerable<short> features;
		
		public ServerOptionalFeaturesMessage()
		{
		}
		
		public ServerOptionalFeaturesMessage(IEnumerable<short> features)
		{
			this.features = features;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)features.Count());
			foreach (var entry in features)
			{
				writer.WriteShort(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			features = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(features as short[])[i] = reader.ReadShort();
			}
		}
	}
}
