// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NicknameChoiceRequestMessage.xml' the '27/06/2012 15:54:56'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class NicknameChoiceRequestMessage : NetworkMessage
	{
		public const uint Id = 5639;
		public override uint MessageId
		{
			get
			{
				return 5639;
			}
		}
		
		public string nickname;
		
		public NicknameChoiceRequestMessage()
		{
		}
		
		public NicknameChoiceRequestMessage(string nickname)
		{
			this.nickname = nickname;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(nickname);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			nickname = reader.ReadUTF();
		}
	}
}
