// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NicknameAcceptedMessage.xml' the '27/06/2012 15:54:56'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class NicknameAcceptedMessage : NetworkMessage
	{
		public const uint Id = 5641;
		public override uint MessageId
		{
			get
			{
				return 5641;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
