// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'LocalizedChatSmileyMessage.xml' the '27/06/2012 15:54:59'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class LocalizedChatSmileyMessage : ChatSmileyMessage
	{
		public const uint Id = 6185;
		public override uint MessageId
		{
			get
			{
				return 6185;
			}
		}
		
		public short cellId;
		
		public LocalizedChatSmileyMessage()
		{
		}
		
		public LocalizedChatSmileyMessage(int entityId, sbyte smileyId, int accountId, short cellId)
			 : base(entityId, smileyId, accountId)
		{
			this.cellId = cellId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(cellId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			cellId = reader.ReadShort();
			if ( cellId < 0 || cellId > 559 )
			{
				throw new Exception("Forbidden value on cellId = " + cellId + ", it doesn't respect the following condition : cellId < 0 || cellId > 559");
			}
		}
	}
}
