// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PrismFightAttackedMessage.xml' the '27/06/2012 15:55:12'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PrismFightAttackedMessage : NetworkMessage
	{
		public const uint Id = 5894;
		public override uint MessageId
		{
			get
			{
				return 5894;
			}
		}
		
		public short worldX;
		public short worldY;
		public int mapId;
		public short subAreaId;
		public sbyte prismSide;
		
		public PrismFightAttackedMessage()
		{
		}
		
		public PrismFightAttackedMessage(short worldX, short worldY, int mapId, short subAreaId, sbyte prismSide)
		{
			this.worldX = worldX;
			this.worldY = worldY;
			this.mapId = mapId;
			this.subAreaId = subAreaId;
			this.prismSide = prismSide;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(worldX);
			writer.WriteShort(worldY);
			writer.WriteInt(mapId);
			writer.WriteShort(subAreaId);
			writer.WriteSByte(prismSide);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			worldX = reader.ReadShort();
			if ( worldX < -255 || worldX > 255 )
			{
				throw new Exception("Forbidden value on worldX = " + worldX + ", it doesn't respect the following condition : worldX < -255 || worldX > 255");
			}
			worldY = reader.ReadShort();
			if ( worldY < -255 || worldY > 255 )
			{
				throw new Exception("Forbidden value on worldY = " + worldY + ", it doesn't respect the following condition : worldY < -255 || worldY > 255");
			}
			mapId = reader.ReadInt();
			subAreaId = reader.ReadShort();
			if ( subAreaId < 0 )
			{
				throw new Exception("Forbidden value on subAreaId = " + subAreaId + ", it doesn't respect the following condition : subAreaId < 0");
			}
			prismSide = reader.ReadSByte();
		}
	}
}
