// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PrismWorldInformationRequestMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PrismWorldInformationRequestMessage : NetworkMessage
	{
		public const uint Id = 5985;
		public override uint MessageId
		{
			get
			{
				return 5985;
			}
		}
		
		public bool join;
		
		public PrismWorldInformationRequestMessage()
		{
		}
		
		public PrismWorldInformationRequestMessage(bool join)
		{
			this.join = join;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(join);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			join = reader.ReadBoolean();
		}
	}
}
