// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PrismInfoValidMessage.xml' the '27/06/2012 15:55:12'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PrismInfoValidMessage : NetworkMessage
	{
		public const uint Id = 5858;
		public override uint MessageId
		{
			get
			{
				return 5858;
			}
		}
		
		public Types.ProtectedEntityWaitingForHelpInfo waitingForHelpInfo;
		
		public PrismInfoValidMessage()
		{
		}
		
		public PrismInfoValidMessage(Types.ProtectedEntityWaitingForHelpInfo waitingForHelpInfo)
		{
			this.waitingForHelpInfo = waitingForHelpInfo;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			waitingForHelpInfo.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			waitingForHelpInfo = new Types.ProtectedEntityWaitingForHelpInfo();
			waitingForHelpInfo.Deserialize(reader);
		}
	}
}
