// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildMember.xml' the '27/06/2012 15:55:17'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class GuildMember : CharacterMinimalInformations
	{
		public const uint Id = 88;
		public override short TypeId
		{
			get
			{
				return 88;
			}
		}
		
		public sbyte breed;
		public bool sex;
		public short rank;
		public double givenExperience;
		public sbyte experienceGivenPercent;
		public uint rights;
		public sbyte connected;
		public sbyte alignmentSide;
		public ushort hoursSinceLastConnection;
		public sbyte moodSmileyId;
		
		public GuildMember()
		{
		}
		
		public GuildMember(int id, byte level, string name, sbyte breed, bool sex, short rank, double givenExperience, sbyte experienceGivenPercent, uint rights, sbyte connected, sbyte alignmentSide, ushort hoursSinceLastConnection, sbyte moodSmileyId)
			 : base(id, level, name)
		{
			this.breed = breed;
			this.sex = sex;
			this.rank = rank;
			this.givenExperience = givenExperience;
			this.experienceGivenPercent = experienceGivenPercent;
			this.rights = rights;
			this.connected = connected;
			this.alignmentSide = alignmentSide;
			this.hoursSinceLastConnection = hoursSinceLastConnection;
			this.moodSmileyId = moodSmileyId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteSByte(breed);
			writer.WriteBoolean(sex);
			writer.WriteShort(rank);
			writer.WriteDouble(givenExperience);
			writer.WriteSByte(experienceGivenPercent);
			writer.WriteUInt(rights);
			writer.WriteSByte(connected);
			writer.WriteSByte(alignmentSide);
			writer.WriteUShort(hoursSinceLastConnection);
			writer.WriteSByte(moodSmileyId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			breed = reader.ReadSByte();
			sex = reader.ReadBoolean();
			rank = reader.ReadShort();
			if ( rank < 0 )
			{
				throw new Exception("Forbidden value on rank = " + rank + ", it doesn't respect the following condition : rank < 0");
			}
			givenExperience = reader.ReadDouble();
			if ( givenExperience < 0 )
			{
				throw new Exception("Forbidden value on givenExperience = " + givenExperience + ", it doesn't respect the following condition : givenExperience < 0");
			}
			experienceGivenPercent = reader.ReadSByte();
			if ( experienceGivenPercent < 0 || experienceGivenPercent > 100 )
			{
				throw new Exception("Forbidden value on experienceGivenPercent = " + experienceGivenPercent + ", it doesn't respect the following condition : experienceGivenPercent < 0 || experienceGivenPercent > 100");
			}
			rights = reader.ReadUInt();
			if ( rights < 0 || rights > 4294967295 )
			{
				throw new Exception("Forbidden value on rights = " + rights + ", it doesn't respect the following condition : rights < 0 || rights > 4294967295");
			}
			connected = reader.ReadSByte();
			if ( connected < 0 )
			{
				throw new Exception("Forbidden value on connected = " + connected + ", it doesn't respect the following condition : connected < 0");
			}
			alignmentSide = reader.ReadSByte();
			hoursSinceLastConnection = reader.ReadUShort();
			if ( hoursSinceLastConnection < 0 || hoursSinceLastConnection > 65535 )
			{
				throw new Exception("Forbidden value on hoursSinceLastConnection = " + hoursSinceLastConnection + ", it doesn't respect the following condition : hoursSinceLastConnection < 0 || hoursSinceLastConnection > 65535");
			}
			moodSmileyId = reader.ReadSByte();
		}
	}
}
