// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameDataPaddockObjectListAddMessage.xml' the '27/06/2012 15:55:01'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Messages
{
	public class GameDataPaddockObjectListAddMessage : NetworkMessage
	{
		public const uint Id = 5992;
		public override uint MessageId
		{
			get
			{
				return 5992;
			}
		}
		
		public IEnumerable<Types.PaddockItem> paddockItemDescription;
		
		public GameDataPaddockObjectListAddMessage()
		{
		}
		
		public GameDataPaddockObjectListAddMessage(IEnumerable<Types.PaddockItem> paddockItemDescription)
		{
			this.paddockItemDescription = paddockItemDescription;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)paddockItemDescription.Count());
			foreach (var entry in paddockItemDescription)
			{
				entry.Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			paddockItemDescription = new Types.PaddockItem[limit];
			for (int i = 0; i < limit; i++)
			{
				(paddockItemDescription as Types.PaddockItem[])[i] = new Types.PaddockItem();
				(paddockItemDescription as Types.PaddockItem[])[i].Deserialize(reader);
			}
		}
	}
}
