// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountSetXpRatioRequestMessage.xml' the '27/06/2012 15:55:01'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class MountSetXpRatioRequestMessage : NetworkMessage
	{
		public const uint Id = 5989;
		public override uint MessageId
		{
			get
			{
				return 5989;
			}
		}
		
		public sbyte xpRatio;
		
		public MountSetXpRatioRequestMessage()
		{
		}
		
		public MountSetXpRatioRequestMessage(sbyte xpRatio)
		{
			this.xpRatio = xpRatio;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(xpRatio);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			xpRatio = reader.ReadSByte();
			if ( xpRatio < 0 )
			{
				throw new Exception("Forbidden value on xpRatio = " + xpRatio + ", it doesn't respect the following condition : xpRatio < 0");
			}
		}
	}
}
