// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountDataMessage.xml' the '27/06/2012 15:55:01'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class MountDataMessage : NetworkMessage
	{
		public const uint Id = 5973;
		public override uint MessageId
		{
			get
			{
				return 5973;
			}
		}
		
		public Types.MountClientData mountData;
		
		public MountDataMessage()
		{
		}
		
		public MountDataMessage(Types.MountClientData mountData)
		{
			this.mountData = mountData;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			mountData.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			mountData = new Types.MountClientData();
			mountData.Deserialize(reader);
		}
	}
}
