// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountEquipedErrorMessage.xml' the '27/06/2012 15:55:01'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class MountEquipedErrorMessage : NetworkMessage
	{
		public const uint Id = 5963;
		public override uint MessageId
		{
			get
			{
				return 5963;
			}
		}
		
		public sbyte errorType;
		
		public MountEquipedErrorMessage()
		{
		}
		
		public MountEquipedErrorMessage(sbyte errorType)
		{
			this.errorType = errorType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(errorType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			errorType = reader.ReadSByte();
			if ( errorType < 0 )
			{
				throw new Exception("Forbidden value on errorType = " + errorType + ", it doesn't respect the following condition : errorType < 0");
			}
		}
	}
}
