// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightOptionsInformations.xml' the '27/06/2012 15:55:15'
using System;
using BiM.Core.IO;
using BiM.Protocol.Messages;

namespace BiM.Protocol.Types
{
	public class FightOptionsInformations
	{
		public const uint Id = 20;
		public virtual short TypeId
		{
			get
			{
				return 20;
			}
		}
		
		public bool isSecret;
		public bool isRestrictedToPartyOnly;
		public bool isClosed;
		public bool isAskingForHelp;
		
		public FightOptionsInformations()
		{
		}
		
		public FightOptionsInformations(bool isSecret, bool isRestrictedToPartyOnly, bool isClosed, bool isAskingForHelp)
		{
			this.isSecret = isSecret;
			this.isRestrictedToPartyOnly = isRestrictedToPartyOnly;
			this.isClosed = isClosed;
			this.isAskingForHelp = isAskingForHelp;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			byte flag1 = 0;
			flag1 = BooleanByteWrapper.SetFlag(flag1, 0, isSecret);
			flag1 = BooleanByteWrapper.SetFlag(flag1, 1, isRestrictedToPartyOnly);
			flag1 = BooleanByteWrapper.SetFlag(flag1, 2, isClosed);
			flag1 = BooleanByteWrapper.SetFlag(flag1, 3, isAskingForHelp);
			writer.WriteByte(flag1);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			byte flag1 = reader.ReadByte();
			isSecret = BooleanByteWrapper.GetFlag(flag1, 0);
			isRestrictedToPartyOnly = BooleanByteWrapper.GetFlag(flag1, 1);
			isClosed = BooleanByteWrapper.GetFlag(flag1, 2);
			isAskingForHelp = BooleanByteWrapper.GetFlag(flag1, 3);
		}
	}
}
