// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightTeamInformations.xml' the '27/06/2012 15:55:15'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Types
{
	public class FightTeamInformations : AbstractFightTeamInformations
	{
		public const uint Id = 33;
		public override short TypeId
		{
			get
			{
				return 33;
			}
		}
		
		public IEnumerable<Types.FightTeamMemberInformations> teamMembers;
		
		public FightTeamInformations()
		{
		}
		
		public FightTeamInformations(sbyte teamId, int leaderId, sbyte teamSide, sbyte teamTypeId, IEnumerable<Types.FightTeamMemberInformations> teamMembers)
			 : base(teamId, leaderId, teamSide, teamTypeId)
		{
			this.teamMembers = teamMembers;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteUShort((ushort)teamMembers.Count());
			foreach (var entry in teamMembers)
			{
				writer.WriteShort(entry.TypeId);
				entry.Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			int limit = reader.ReadUShort();
			teamMembers = new Types.FightTeamMemberInformations[limit];
			for (int i = 0; i < limit; i++)
			{
				(teamMembers as Types.FightTeamMemberInformations[])[i] = ProtocolTypeManager.GetInstance<Types.FightTeamMemberInformations>(reader.ReadShort());
				(teamMembers as Types.FightTeamMemberInformations[])[i].Deserialize(reader);
			}
		}
	}
}
