// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'LockableChangeCodeMessage.xml' the '27/06/2012 15:55:03'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class LockableChangeCodeMessage : NetworkMessage
	{
		public const uint Id = 5666;
		public override uint MessageId
		{
			get
			{
				return 5666;
			}
		}
		
		public string code;
		
		public LockableChangeCodeMessage()
		{
		}
		
		public LockableChangeCodeMessage(string code)
		{
			this.code = code;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(code);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			code = reader.ReadUTF();
		}
	}
}
