// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SubscriptionZoneMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class SubscriptionZoneMessage : NetworkMessage
	{
		public const uint Id = 5573;
		public override uint MessageId
		{
			get
			{
				return 5573;
			}
		}
		
		public bool active;
		
		public SubscriptionZoneMessage()
		{
		}
		
		public SubscriptionZoneMessage(bool active)
		{
			this.active = active;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(active);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			active = reader.ReadBoolean();
		}
	}
}
