// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeleportDestinationsListMessage.xml' the '27/06/2012 15:55:08'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class TeleportDestinationsListMessage : NetworkMessage
	{
		public const uint Id = 5960;
		public override uint MessageId
		{
			get
			{
				return 5960;
			}
		}
		
		public sbyte teleporterType;
		public int[] mapIds;
		public short[] subAreaIds;
		public short[] costs;
		
		public TeleportDestinationsListMessage()
		{
		}
		
		public TeleportDestinationsListMessage(sbyte teleporterType, int[] mapIds, short[] subAreaIds, short[] costs)
		{
			this.teleporterType = teleporterType;
			this.mapIds = mapIds;
			this.subAreaIds = subAreaIds;
			this.costs = costs;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(teleporterType);
			writer.WriteUShort((ushort)mapIds.Count());
			foreach (var entry in mapIds)
			{
				writer.WriteInt(entry);
			}
			writer.WriteUShort((ushort)subAreaIds.Count());
			foreach (var entry in subAreaIds)
			{
				writer.WriteShort(entry);
			}
			writer.WriteUShort((ushort)costs.Count());
			foreach (var entry in costs)
			{
				writer.WriteShort(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			teleporterType = reader.ReadSByte();
			if ( teleporterType < 0 )
			{
				throw new Exception("Forbidden value on teleporterType = " + teleporterType + ", it doesn't respect the following condition : teleporterType < 0");
			}
			int limit = reader.ReadUShort();
			mapIds = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				(mapIds as int[])[i] = reader.ReadInt();
			}
			limit = reader.ReadUShort();
			subAreaIds = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(subAreaIds as short[])[i] = reader.ReadShort();
			}
			limit = reader.ReadUShort();
			costs = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(costs as short[])[i] = reader.ReadShort();
			}
		}
	}
}
