// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'HouseGuildRightsViewMessage.xml' the '27/06/2012 15:55:03'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class HouseGuildRightsViewMessage : NetworkMessage
	{
		public const uint Id = 5700;
		public override uint MessageId
		{
			get
			{
				return 5700;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
