// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CurrentMapMessage.xml' the '27/06/2012 15:55:02'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class CurrentMapMessage : NetworkMessage
	{
		public const uint Id = 220;
		public override uint MessageId
		{
			get
			{
				return 220;
			}
		}
		
		public int mapId;
		public string mapKey;
		
		public CurrentMapMessage()
		{
		}
		
		public CurrentMapMessage(int mapId, string mapKey)
		{
			this.mapId = mapId;
			this.mapKey = mapKey;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(mapId);
			writer.WriteUTF(mapKey);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			mapId = reader.ReadInt();
			if ( mapId < 0 )
			{
				throw new Exception("Forbidden value on mapId = " + mapId + ", it doesn't respect the following condition : mapId < 0");
			}
			mapKey = reader.ReadUTF();
		}
	}
}
