// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutBarRemoveRequestMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class ShortcutBarRemoveRequestMessage : NetworkMessage
	{
		public const uint Id = 6228;
		public override uint MessageId
		{
			get
			{
				return 6228;
			}
		}
		
		public sbyte barType;
		public int slot;
		
		public ShortcutBarRemoveRequestMessage()
		{
		}
		
		public ShortcutBarRemoveRequestMessage(sbyte barType, int slot)
		{
			this.barType = barType;
			this.slot = slot;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(barType);
			writer.WriteInt(slot);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			barType = reader.ReadSByte();
			if ( barType < 0 )
			{
				throw new Exception("Forbidden value on barType = " + barType + ", it doesn't respect the following condition : barType < 0");
			}
			slot = reader.ReadInt();
			if ( slot < 0 || slot > 99 )
			{
				throw new Exception("Forbidden value on slot = " + slot + ", it doesn't respect the following condition : slot < 0 || slot > 99");
			}
		}
	}
}
