// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AbstractGameActionMessage.xml' the '27/06/2012 15:54:56'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class AbstractGameActionMessage : NetworkMessage
	{
		public const uint Id = 1000;
		public override uint MessageId
		{
			get
			{
				return 1000;
			}
		}
		
		public short actionId;
		public int sourceId;
		
		public AbstractGameActionMessage()
		{
		}
		
		public AbstractGameActionMessage(short actionId, int sourceId)
		{
			this.actionId = actionId;
			this.sourceId = sourceId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(actionId);
			writer.WriteInt(sourceId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			actionId = reader.ReadShort();
			if ( actionId < 0 )
			{
				throw new Exception("Forbidden value on actionId = " + actionId + ", it doesn't respect the following condition : actionId < 0");
			}
			sourceId = reader.ReadInt();
		}
	}
}
