// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BasicSwitchModeRequestMessage.xml' the '27/06/2012 15:54:58'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class BasicSwitchModeRequestMessage : NetworkMessage
	{
		public const uint Id = 6101;
		public override uint MessageId
		{
			get
			{
				return 6101;
			}
		}
		
		public sbyte mode;
		
		public BasicSwitchModeRequestMessage()
		{
		}
		
		public BasicSwitchModeRequestMessage(sbyte mode)
		{
			this.mode = mode;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(mode);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			mode = reader.ReadSByte();
		}
	}
}
