// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NumericWhoIsMessage.xml' the '27/06/2012 15:54:58'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class NumericWhoIsMessage : NetworkMessage
	{
		public const uint Id = 6297;
		public override uint MessageId
		{
			get
			{
				return 6297;
			}
		}
		
		public int playerId;
		public int accountId;
		
		public NumericWhoIsMessage()
		{
		}
		
		public NumericWhoIsMessage(int playerId, int accountId)
		{
			this.playerId = playerId;
			this.accountId = accountId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(playerId);
			writer.WriteInt(accountId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			playerId = reader.ReadInt();
			if ( playerId < 0 )
			{
				throw new Exception("Forbidden value on playerId = " + playerId + ", it doesn't respect the following condition : playerId < 0");
			}
			accountId = reader.ReadInt();
			if ( accountId < 0 )
			{
				throw new Exception("Forbidden value on accountId = " + accountId + ", it doesn't respect the following condition : accountId < 0");
			}
		}
	}
}
