// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectEffectString.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class ObjectEffectString : ObjectEffect
	{
		public const uint Id = 74;
		public override short TypeId
		{
			get
			{
				return 74;
			}
		}
		
		public string value;
		
		public ObjectEffectString()
		{
		}
		
		public ObjectEffectString(short actionId, string value)
			 : base(actionId)
		{
			this.value = value;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteUTF(value);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			value = reader.ReadUTF();
		}
	}
}
