// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectEffectMount.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class ObjectEffectMount : ObjectEffect
	{
		public const uint Id = 179;
		public override short TypeId
		{
			get
			{
				return 179;
			}
		}
		
		public int mountId;
		public double date;
		public short modelId;
		
		public ObjectEffectMount()
		{
		}
		
		public ObjectEffectMount(short actionId, int mountId, double date, short modelId)
			 : base(actionId)
		{
			this.mountId = mountId;
			this.date = date;
			this.modelId = modelId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(mountId);
			writer.WriteDouble(date);
			writer.WriteShort(modelId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			mountId = reader.ReadInt();
			if ( mountId < 0 )
			{
				throw new Exception("Forbidden value on mountId = " + mountId + ", it doesn't respect the following condition : mountId < 0");
			}
			date = reader.ReadDouble();
			modelId = reader.ReadShort();
			if ( modelId < 0 )
			{
				throw new Exception("Forbidden value on modelId = " + modelId + ", it doesn't respect the following condition : modelId < 0");
			}
		}
	}
}
