// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionFightDropCharacterMessage.xml' the '27/06/2012 15:54:56'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class GameActionFightDropCharacterMessage : AbstractGameActionMessage
	{
		public const uint Id = 5826;
		public override uint MessageId
		{
			get
			{
				return 5826;
			}
		}
		
		public int targetId;
		public short cellId;
		
		public GameActionFightDropCharacterMessage()
		{
		}
		
		public GameActionFightDropCharacterMessage(short actionId, int sourceId, int targetId, short cellId)
			 : base(actionId, sourceId)
		{
			this.targetId = targetId;
			this.cellId = cellId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(targetId);
			writer.WriteShort(cellId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			targetId = reader.ReadInt();
			cellId = reader.ReadShort();
			if ( cellId < -1 || cellId > 559 )
			{
				throw new Exception("Forbidden value on cellId = " + cellId + ", it doesn't respect the following condition : cellId < -1 || cellId > 559");
			}
		}
	}
}
