// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionFightDispellableEffectMessage.xml' the '27/06/2012 15:54:56'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class GameActionFightDispellableEffectMessage : AbstractGameActionMessage
	{
		public const uint Id = 6070;
		public override uint MessageId
		{
			get
			{
				return 6070;
			}
		}
		
		public Types.AbstractFightDispellableEffect effect;
		
		public GameActionFightDispellableEffectMessage()
		{
		}
		
		public GameActionFightDispellableEffectMessage(short actionId, int sourceId, Types.AbstractFightDispellableEffect effect)
			 : base(actionId, sourceId)
		{
			this.effect = effect;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(effect.TypeId);
			effect.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			effect = Types.ProtocolTypeManager.GetInstance<Types.AbstractFightDispellableEffect>(reader.ReadShort());
			effect.Deserialize(reader);
		}
	}
}
