// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CredentialsAcknowledgementMessage.xml' the '27/06/2012 15:54:55'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class CredentialsAcknowledgementMessage : NetworkMessage
	{
		public const uint Id = 6314;
		public override uint MessageId
		{
			get
			{
				return 6314;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
