// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'IdentificationFailedForBadVersionMessage.xml' the '27/06/2012 15:54:55'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class IdentificationFailedForBadVersionMessage : IdentificationFailedMessage
	{
		public const uint Id = 21;
		public override uint MessageId
		{
			get
			{
				return 21;
			}
		}
		
		public Types.Version requiredVersion;
		
		public IdentificationFailedForBadVersionMessage()
		{
		}
		
		public IdentificationFailedForBadVersionMessage(sbyte reason, Types.Version requiredVersion)
			 : base(reason)
		{
			this.requiredVersion = requiredVersion;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			requiredVersion.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			requiredVersion = new Types.Version();
			requiredVersion.Deserialize(reader);
		}
	}
}
