// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FriendsListWithSpouseMessage.xml' the '27/06/2012 15:55:06'
using System;
using BiM.Core.IO;
using System.Collections.Generic;

namespace BiM.Protocol.Messages
{
	public class FriendsListWithSpouseMessage : FriendsListMessage
	{
		public const uint Id = 5931;
		public override uint MessageId
		{
			get
			{
				return 5931;
			}
		}
		
		public Types.FriendSpouseInformations spouse;
		
		public FriendsListWithSpouseMessage()
		{
		}
		
		public FriendsListWithSpouseMessage(IEnumerable<Types.FriendInformations> friendsList, Types.FriendSpouseInformations spouse)
			 : base(friendsList)
		{
			this.spouse = spouse;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(spouse.TypeId);
			spouse.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			spouse = Types.ProtocolTypeManager.GetInstance<Types.FriendSpouseInformations>(reader.ReadShort());
			spouse.Deserialize(reader);
		}
	}
}
