// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FriendDeleteResultMessage.xml' the '27/06/2012 15:55:06'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class FriendDeleteResultMessage : NetworkMessage
	{
		public const uint Id = 5601;
		public override uint MessageId
		{
			get
			{
				return 5601;
			}
		}
		
		public bool success;
		public string name;
		
		public FriendDeleteResultMessage()
		{
		}
		
		public FriendDeleteResultMessage(bool success, string name)
		{
			this.success = success;
			this.name = name;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(success);
			writer.WriteUTF(name);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			success = reader.ReadBoolean();
			name = reader.ReadUTF();
		}
	}
}
