// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterReportMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class CharacterReportMessage : NetworkMessage
	{
		public const uint Id = 6079;
		public override uint MessageId
		{
			get
			{
				return 6079;
			}
		}
		
		public uint reportedId;
		public sbyte reason;
		
		public CharacterReportMessage()
		{
		}
		
		public CharacterReportMessage(uint reportedId, sbyte reason)
		{
			this.reportedId = reportedId;
			this.reason = reason;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUInt(reportedId);
			writer.WriteSByte(reason);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			reportedId = reader.ReadUInt();
			if ( reportedId < 0 || reportedId > 4294967295 )
			{
				throw new Exception("Forbidden value on reportedId = " + reportedId + ", it doesn't respect the following condition : reportedId < 0 || reportedId > 4294967295");
			}
			reason = reader.ReadSByte();
			if ( reason < 0 )
			{
				throw new Exception("Forbidden value on reason = " + reason + ", it doesn't respect the following condition : reason < 0");
			}
		}
	}
}
