// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'InteractiveMapUpdateMessage.xml' the '27/06/2012 15:55:08'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class InteractiveMapUpdateMessage : NetworkMessage
	{
		public const uint Id = 5002;
		public override uint MessageId
		{
			get
			{
				return 5002;
			}
		}
		
		public IEnumerable<Types.InteractiveElement> interactiveElements;
		
		public InteractiveMapUpdateMessage()
		{
		}
		
		public InteractiveMapUpdateMessage(IEnumerable<Types.InteractiveElement> interactiveElements)
		{
			this.interactiveElements = interactiveElements;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)interactiveElements.Count());
			foreach (var entry in interactiveElements)
			{
				entry.Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			interactiveElements = new Types.InteractiveElement[limit];
			for (int i = 0; i < limit; i++)
			{
				(interactiveElements as Types.InteractiveElement[])[i] = new Types.InteractiveElement();
				(interactiveElements as Types.InteractiveElement[])[i].Deserialize(reader);
			}
		}
	}
}
