// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StatedElementUpdatedMessage.xml' the '27/06/2012 15:55:08'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class StatedElementUpdatedMessage : NetworkMessage
	{
		public const uint Id = 5709;
		public override uint MessageId
		{
			get
			{
				return 5709;
			}
		}
		
		public Types.StatedElement statedElement;
		
		public StatedElementUpdatedMessage()
		{
		}
		
		public StatedElementUpdatedMessage(Types.StatedElement statedElement)
		{
			this.statedElement = statedElement;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			statedElement.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			statedElement = new Types.StatedElement();
			statedElement.Deserialize(reader);
		}
	}
}
