// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StatedMapUpdateMessage.xml' the '27/06/2012 15:55:08'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Messages
{
	public class StatedMapUpdateMessage : NetworkMessage
	{
		public const uint Id = 5716;
		public override uint MessageId
		{
			get
			{
				return 5716;
			}
		}
		
		public IEnumerable<Types.StatedElement> statedElements;
		
		public StatedMapUpdateMessage()
		{
		}
		
		public StatedMapUpdateMessage(IEnumerable<Types.StatedElement> statedElements)
		{
			this.statedElements = statedElements;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)statedElements.Count());
			foreach (var entry in statedElements)
			{
				entry.Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			statedElements = new Types.StatedElement[limit];
			for (int i = 0; i < limit; i++)
			{
				(statedElements as Types.StatedElement[])[i] = new Types.StatedElement();
				(statedElements as Types.StatedElement[])[i].Deserialize(reader);
			}
		}
	}
}
