// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'UpdateMountBoost.xml' the '27/06/2012 15:55:17'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class UpdateMountBoost
	{
		public const uint Id = 356;
		public virtual short TypeId
		{
			get
			{
				return 356;
			}
		}
		
		public sbyte type;
		
		public UpdateMountBoost()
		{
		}
		
		public UpdateMountBoost(sbyte type)
		{
			this.type = type;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(type);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			type = reader.ReadSByte();
		}
	}
}
