// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AbstractContactInformations.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class AbstractContactInformations
	{
		public const uint Id = 380;
		public virtual short TypeId
		{
			get
			{
				return 380;
			}
		}
		
		public int accountId;
		public string accountName;
		
		public AbstractContactInformations()
		{
		}
		
		public AbstractContactInformations(int accountId, string accountName)
		{
			this.accountId = accountId;
			this.accountName = accountName;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteInt(accountId);
			writer.WriteUTF(accountName);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			accountId = reader.ReadInt();
			if ( accountId < 0 )
			{
				throw new Exception("Forbidden value on accountId = " + accountId + ", it doesn't respect the following condition : accountId < 0");
			}
			accountName = reader.ReadUTF();
		}
	}
}
