// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FriendInformations.xml' the '27/06/2012 15:55:16'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Types
{
	public class FriendInformations : AbstractContactInformations
	{
		public const uint Id = 78;
		public override short TypeId
		{
			get
			{
				return 78;
			}
		}
		
		public sbyte playerState;
		public int lastConnection;
		
		public FriendInformations()
		{
		}
		
		public FriendInformations(int accountId, string accountName, sbyte playerState, int lastConnection)
			 : base(accountId, accountName)
		{
			this.playerState = playerState;
			this.lastConnection = lastConnection;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteSByte(playerState);
			writer.WriteInt(lastConnection);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			playerState = reader.ReadSByte();
			if ( playerState < 0 )
			{
				throw new Exception("Forbidden value on playerState = " + playerState + ", it doesn't respect the following condition : playerState < 0");
			}
			lastConnection = reader.ReadInt();
			if ( lastConnection < 0 )
			{
				throw new Exception("Forbidden value on lastConnection = " + lastConnection + ", it doesn't respect the following condition : lastConnection < 0");
			}
		}
	}
}
