// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ContactLookRequestMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class ContactLookRequestMessage : NetworkMessage
	{
		public const uint Id = 5932;
		public override uint MessageId
		{
			get
			{
				return 5932;
			}
		}
		
		public byte requestId;
		public sbyte contactType;
		
		public ContactLookRequestMessage()
		{
		}
		
		public ContactLookRequestMessage(byte requestId, sbyte contactType)
		{
			this.requestId = requestId;
			this.contactType = contactType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(requestId);
			writer.WriteSByte(contactType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			requestId = reader.ReadByte();
			if ( requestId < 0 || requestId > 255 )
			{
				throw new Exception("Forbidden value on requestId = " + requestId + ", it doesn't respect the following condition : requestId < 0 || requestId > 255");
			}
			contactType = reader.ReadSByte();
			if ( contactType < 0 )
			{
				throw new Exception("Forbidden value on contactType = " + contactType + ", it doesn't respect the following condition : contactType < 0");
			}
		}
	}
}
