// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildFightJoinRequestMessage.xml' the '27/06/2012 15:55:07'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class GuildFightJoinRequestMessage : NetworkMessage
	{
		public const uint Id = 5717;
		public override uint MessageId
		{
			get
			{
				return 5717;
			}
		}
		
		public int taxCollectorId;
		
		public GuildFightJoinRequestMessage()
		{
		}
		
		public GuildFightJoinRequestMessage(int taxCollectorId)
		{
			this.taxCollectorId = taxCollectorId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(taxCollectorId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			taxCollectorId = reader.ReadInt();
		}
	}
}
