// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AtlasPointInformationsMessage.xml' the '27/06/2012 15:54:58'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class AtlasPointInformationsMessage : NetworkMessage
	{
		public const uint Id = 5956;
		public override uint MessageId
		{
			get
			{
				return 5956;
			}
		}
		
		public Types.AtlasPointsInformations type;
		
		public AtlasPointInformationsMessage()
		{
		}
		
		public AtlasPointInformationsMessage(Types.AtlasPointsInformations type)
		{
			this.type = type;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			type.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			type = new Types.AtlasPointsInformations();
			type.Deserialize(reader);
		}
	}
}
