// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TaxCollectorDialogQuestionBasicMessage.xml' the '27/06/2012 15:55:03'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class TaxCollectorDialogQuestionBasicMessage : NetworkMessage
	{
		public const uint Id = 5619;
		public override uint MessageId
		{
			get
			{
				return 5619;
			}
		}
		
		public Types.BasicGuildInformations guildInfo;
		
		public TaxCollectorDialogQuestionBasicMessage()
		{
		}
		
		public TaxCollectorDialogQuestionBasicMessage(Types.BasicGuildInformations guildInfo)
		{
			this.guildInfo = guildInfo;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			guildInfo.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			guildInfo = new Types.BasicGuildInformations();
			guildInfo.Deserialize(reader);
		}
	}
}
