// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StorageInventoryContentMessage.xml' the '27/06/2012 15:55:12'
using System;
using BiM.Core.IO;
using System.Collections.Generic;

namespace BiM.Protocol.Messages
{
	public class StorageInventoryContentMessage : InventoryContentMessage
	{
		public const uint Id = 5646;
		public override uint MessageId
		{
			get
			{
				return 5646;
			}
		}
		
		
		public StorageInventoryContentMessage()
		{
		}
		
		public StorageInventoryContentMessage(IEnumerable<Types.ObjectItem> objects, int kamas)
			 : base(objects, kamas)
		{
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
		}
	}
}
