// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'DungeonPartyFinderListenRequestMessage.xml' the '27/06/2012 15:55:04'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class DungeonPartyFinderListenRequestMessage : NetworkMessage
	{
		public const uint Id = 6246;
		public override uint MessageId
		{
			get
			{
				return 6246;
			}
		}
		
		public short dungeonId;
		
		public DungeonPartyFinderListenRequestMessage()
		{
		}
		
		public DungeonPartyFinderListenRequestMessage(short dungeonId)
		{
			this.dungeonId = dungeonId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(dungeonId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			dungeonId = reader.ReadShort();
			if ( dungeonId < 0 )
			{
				throw new Exception("Forbidden value on dungeonId = " + dungeonId + ", it doesn't respect the following condition : dungeonId < 0");
			}
		}
	}
}
