// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'DungeonPartyFinderRegisterRequestMessage.xml' the '27/06/2012 15:55:04'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace BiM.Protocol.Messages
{
	public class DungeonPartyFinderRegisterRequestMessage : NetworkMessage
	{
		public const uint Id = 6249;
		public override uint MessageId
		{
			get
			{
				return 6249;
			}
		}
		
		public IEnumerable<short> dungeonIds;
		
		public DungeonPartyFinderRegisterRequestMessage()
		{
		}
		
		public DungeonPartyFinderRegisterRequestMessage(IEnumerable<short> dungeonIds)
		{
			this.dungeonIds = dungeonIds;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)dungeonIds.Count());
			foreach (var entry in dungeonIds)
			{
				writer.WriteShort(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			dungeonIds = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(dungeonIds as short[])[i] = reader.ReadShort();
			}
		}
	}
}
