// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyLeaveRequestMessage.xml' the '27/06/2012 15:55:05'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PartyLeaveRequestMessage : AbstractPartyMessage
	{
		public const uint Id = 5593;
		public override uint MessageId
		{
			get
			{
				return 5593;
			}
		}
		
		
		public PartyLeaveRequestMessage()
		{
		}
		
		public PartyLeaveRequestMessage(int partyId)
			 : base(partyId)
		{
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
		}
	}
}
