// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyInvitationDetailsRequestMessage.xml' the '27/06/2012 15:55:04'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PartyInvitationDetailsRequestMessage : AbstractPartyMessage
	{
		public const uint Id = 6264;
		public override uint MessageId
		{
			get
			{
				return 6264;
			}
		}
		
		
		public PartyInvitationDetailsRequestMessage()
		{
		}
		
		public PartyInvitationDetailsRequestMessage(int partyId)
			 : base(partyId)
		{
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
		}
	}
}
