// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyUpdateMessage.xml' the '27/06/2012 15:55:05'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PartyUpdateMessage : AbstractPartyEventMessage
	{
		public const uint Id = 5575;
		public override uint MessageId
		{
			get
			{
				return 5575;
			}
		}
		
		public Types.PartyMemberInformations memberInformations;
		
		public PartyUpdateMessage()
		{
		}
		
		public PartyUpdateMessage(int partyId, Types.PartyMemberInformations memberInformations)
			 : base(partyId)
		{
			this.memberInformations = memberInformations;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(memberInformations.TypeId);
			memberInformations.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			memberInformations = Types.ProtocolTypeManager.GetInstance<Types.PartyMemberInformations>(reader.ReadShort());
			memberInformations.Deserialize(reader);
		}
	}
}
