// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyInvitationRequestMessage.xml' the '27/06/2012 15:55:05'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class PartyInvitationRequestMessage : NetworkMessage
	{
		public const uint Id = 5585;
		public override uint MessageId
		{
			get
			{
				return 5585;
			}
		}
		
		public string name;
		
		public PartyInvitationRequestMessage()
		{
		}
		
		public PartyInvitationRequestMessage(string name)
		{
			this.name = name;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(name);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			name = reader.ReadUTF();
		}
	}
}
