// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyInvitationArenaRequestMessage.xml' the '27/06/2012 15:55:04'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PartyInvitationArenaRequestMessage : PartyInvitationRequestMessage
	{
		public const uint Id = 6283;
		public override uint MessageId
		{
			get
			{
				return 6283;
			}
		}
		
		
		public PartyInvitationArenaRequestMessage()
		{
		}
		
		public PartyInvitationArenaRequestMessage(string name)
			 : base(name)
		{
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
		}
	}
}
