// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyLoyaltyStatusMessage.xml' the '27/06/2012 15:55:05'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class PartyLoyaltyStatusMessage : AbstractPartyMessage
	{
		public const uint Id = 6270;
		public override uint MessageId
		{
			get
			{
				return 6270;
			}
		}
		
		public bool loyal;
		
		public PartyLoyaltyStatusMessage()
		{
		}
		
		public PartyLoyaltyStatusMessage(int partyId, bool loyal)
			 : base(partyId)
		{
			this.loyal = loyal;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteBoolean(loyal);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			loyal = reader.ReadBoolean();
		}
	}
}
