// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightTurnReadyMessage.xml' the '27/06/2012 15:55:01'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class GameFightTurnReadyMessage : NetworkMessage
	{
		public const uint Id = 716;
		public override uint MessageId
		{
			get
			{
				return 716;
			}
		}
		
		public bool isReady;
		
		public GameFightTurnReadyMessage()
		{
		}
		
		public GameFightTurnReadyMessage(bool isReady)
		{
			this.isReady = isReady;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(isReady);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			isReady = reader.ReadBoolean();
		}
	}
}
