// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightStartMessage.xml' the '27/06/2012 15:55:00'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class GameFightStartMessage : NetworkMessage
	{
		public const uint Id = 712;
		public override uint MessageId
		{
			get
			{
				return 712;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
