// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightTurnEndMessage.xml' the '27/06/2012 15:55:01'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class GameFightTurnEndMessage : NetworkMessage
	{
		public const uint Id = 719;
		public override uint MessageId
		{
			get
			{
				return 719;
			}
		}
		
		public int id;
		
		public GameFightTurnEndMessage()
		{
		}
		
		public GameFightTurnEndMessage(int id)
		{
			this.id = id;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(id);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			id = reader.ReadInt();
		}
	}
}
