// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightNewRoundMessage.xml' the '27/06/2012 15:55:00'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class GameFightNewRoundMessage : NetworkMessage
	{
		public const uint Id = 6239;
		public override uint MessageId
		{
			get
			{
				return 6239;
			}
		}
		
		public int roundNumber;
		
		public GameFightNewRoundMessage()
		{
		}
		
		public GameFightNewRoundMessage(int roundNumber)
		{
			this.roundNumber = roundNumber;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(roundNumber);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			roundNumber = reader.ReadInt();
			if ( roundNumber < 0 )
			{
				throw new Exception("Forbidden value on roundNumber = " + roundNumber + ", it doesn't respect the following condition : roundNumber < 0");
			}
		}
	}
}
