// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightHumanReadyStateMessage.xml' the '27/06/2012 15:55:00'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class GameFightHumanReadyStateMessage : NetworkMessage
	{
		public const uint Id = 740;
		public override uint MessageId
		{
			get
			{
				return 740;
			}
		}
		
		public int characterId;
		public bool isReady;
		
		public GameFightHumanReadyStateMessage()
		{
		}
		
		public GameFightHumanReadyStateMessage(int characterId, bool isReady)
		{
			this.characterId = characterId;
			this.isReady = isReady;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(characterId);
			writer.WriteBoolean(isReady);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			characterId = reader.ReadInt();
			if ( characterId < 0 )
			{
				throw new Exception("Forbidden value on characterId = " + characterId + ", it doesn't respect the following condition : characterId < 0");
			}
			isReady = reader.ReadBoolean();
		}
	}
}
