// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectUseOnCharacterMessage.xml' the '27/06/2012 15:55:12'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ObjectUseOnCharacterMessage : ObjectUseMessage
	{
		public const uint Id = 3003;
		public override uint MessageId
		{
			get
			{
				return 3003;
			}
		}
		
		public int characterId;
		
		public ObjectUseOnCharacterMessage()
		{
		}
		
		public ObjectUseOnCharacterMessage(int objectUID, int characterId)
			 : base(objectUID)
		{
			this.characterId = characterId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(characterId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			characterId = reader.ReadInt();
			if ( characterId < 0 )
			{
				throw new Exception("Forbidden value on characterId = " + characterId + ", it doesn't respect the following condition : characterId < 0");
			}
		}
	}
}
