// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectUseOnCellMessage.xml' the '27/06/2012 15:55:12'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ObjectUseOnCellMessage : ObjectUseMessage
	{
		public const uint Id = 3013;
		public override uint MessageId
		{
			get
			{
				return 3013;
			}
		}
		
		public short cells;
		
		public ObjectUseOnCellMessage()
		{
		}
		
		public ObjectUseOnCellMessage(int objectUID, short cells)
			 : base(objectUID)
		{
			this.cells = cells;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(cells);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			cells = reader.ReadShort();
			if ( cells < 0 || cells > 559 )
			{
				throw new Exception("Forbidden value on cells = " + cells + ", it doesn't respect the following condition : cells < 0 || cells > 559");
			}
		}
	}
}
