// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectAddedMessage.xml' the '27/06/2012 15:55:11'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ObjectAddedMessage : NetworkMessage
	{
		public const uint Id = 3025;
		public override uint MessageId
		{
			get
			{
				return 3025;
			}
		}
		
		public Types.ObjectItem @object;
		
		public ObjectAddedMessage()
		{
		}
		
		public ObjectAddedMessage(Types.ObjectItem @object)
		{
			this.@object = @object;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			@object.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			@object = new Types.ObjectItem();
			@object.Deserialize(reader);
		}
	}
}
