// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChatClientPrivateMessage.xml' the '27/06/2012 15:54:59'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ChatClientPrivateMessage : ChatAbstractClientMessage
	{
		public const uint Id = 851;
		public override uint MessageId
		{
			get
			{
				return 851;
			}
		}
		
		public string receiver;
		
		public ChatClientPrivateMessage()
		{
		}
		
		public ChatClientPrivateMessage(string content, string receiver)
			 : base(content)
		{
			this.receiver = receiver;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteUTF(receiver);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			receiver = reader.ReadUTF();
		}
	}
}
