// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChatClientMultiMessage.xml' the '27/06/2012 15:54:59'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class ChatClientMultiMessage : ChatAbstractClientMessage
	{
		public const uint Id = 861;
		public override uint MessageId
		{
			get
			{
				return 861;
			}
		}
		
		public sbyte channel;
		
		public ChatClientMultiMessage()
		{
		}
		
		public ChatClientMultiMessage(string content, sbyte channel)
			 : base(content)
		{
			this.channel = channel;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteSByte(channel);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			channel = reader.ReadSByte();
			if ( channel < 0 )
			{
				throw new Exception("Forbidden value on channel = " + channel + ", it doesn't respect the following condition : channel < 0");
			}
		}
	}
}
