// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildInformationsMembersMessage.xml' the '27/06/2012 15:55:07'
using System;
using BiM.Core.IO;
using System.Collections.Generic;
using System.Linq;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class GuildInformationsMembersMessage : NetworkMessage
	{
		public const uint Id = 5558;
		public override uint MessageId
		{
			get
			{
				return 5558;
			}
		}
		
		public IEnumerable<Types.GuildMember> members;
		
		public GuildInformationsMembersMessage()
		{
		}
		
		public GuildInformationsMembersMessage(IEnumerable<Types.GuildMember> members)
		{
			this.members = members;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)members.Count());
			foreach (var entry in members)
			{
				entry.Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			members = new Types.GuildMember[limit];
			for (int i = 0; i < limit; i++)
			{
				(members as Types.GuildMember[])[i] = new Types.GuildMember();
				(members as Types.GuildMember[])[i].Deserialize(reader);
			}
		}
	}
}
