// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildPaddockTeleportRequestMessage.xml' the '27/06/2012 15:55:07'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class GuildPaddockTeleportRequestMessage : NetworkMessage
	{
		public const uint Id = 5957;
		public override uint MessageId
		{
			get
			{
				return 5957;
			}
		}
		
		public int paddockId;
		
		public GuildPaddockTeleportRequestMessage()
		{
		}
		
		public GuildPaddockTeleportRequestMessage(int paddockId)
		{
			this.paddockId = paddockId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(paddockId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			paddockId = reader.ReadInt();
		}
	}
}
