// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildLevelUpMessage.xml' the '27/06/2012 15:55:07'
using System;
using BiM.Core.IO;

namespace BiM.Protocol.Messages
{
	public class GuildLevelUpMessage : NetworkMessage
	{
		public const uint Id = 6062;
		public override uint MessageId
		{
			get
			{
				return 6062;
			}
		}
		
		public byte newLevel;
		
		public GuildLevelUpMessage()
		{
		}
		
		public GuildLevelUpMessage(byte newLevel)
		{
			this.newLevel = newLevel;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteByte(newLevel);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			newLevel = reader.ReadByte();
			if ( newLevel < 2 || newLevel > 200 )
			{
				throw new Exception("Forbidden value on newLevel = " + newLevel + ", it doesn't respect the following condition : newLevel < 2 || newLevel > 200");
			}
		}
	}
}
