// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildMemberOnlineStatusMessage.xml' the '27/06/2012 15:55:07'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class GuildMemberOnlineStatusMessage : NetworkMessage
	{
		public const uint Id = 6061;
		public override uint MessageId
		{
			get
			{
				return 6061;
			}
		}
		
		public int memberId;
		public bool online;
		
		public GuildMemberOnlineStatusMessage()
		{
		}
		
		public GuildMemberOnlineStatusMessage(int memberId, bool online)
		{
			this.memberId = memberId;
			this.online = online;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(memberId);
			writer.WriteBoolean(online);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			memberId = reader.ReadInt();
			if ( memberId < 0 )
			{
				throw new Exception("Forbidden value on memberId = " + memberId + ", it doesn't respect the following condition : memberId < 0");
			}
			online = reader.ReadBoolean();
		}
	}
}
