// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'RawDataMessage.xml' the '27/06/2012 15:55:13'
using System;
using BiM.Core.IO;
using BiM.Core.Network;

namespace BiM.Protocol.Messages
{
	public class RawDataMessage : NetworkMessage
	{
		public const uint Id = 6253;
		public override uint MessageId
		{
			get
			{
				return 6253;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
